steps:
  - name: "Set up Micromamba"
    uses: mamba-org/setup-micromamba@v2
    with:
      environment-name: pytensor-test
      micromamba-version: "1.5.10-0"
      init-shell: bash
      post-cleanup: "all"
      create-args: python=3.13

  - name: "Install dependencies"
    shell: micromamba-shell {0}
    run: |
      micromamba install --yes -q -c conda-forge python=3.13 mkl "numpy>=2.0" scipy pip mkl-service graphviz cython pytest coverage pytest-cov pytest-benchmark pytest-mock pytest-sphinx
      micromamba install --yes -q -c conda-forge "numba>=0.57"
      micromamba install --yes -q -c conda-forge jax jaxlib numpyro equinox
      pip install tfp-nightly
      pip install -e ./
