# This issue template was adapted from the NumPy project
# under the BSD 3-Clause "New" or "Revised" License.
# Copyright (c) 2005-2022, NumPy Developers.
# All rights reserved.

name: Feature request
description: Check instructions for submitting your idea on the mailing list first.
title: "ENH: <Please write a comprehensive title after the 'ENH: ' prefix>"
labels: [feature request]


body:
- type: markdown
  attributes:
    value: >
      If you're looking to request a new feature or change in functionality,
      including adding or changing the meaning of arguments to an existing
      function, please post your idea first on please create a discussion thread at
      [Discussions](https://github.com/pymc-devs/pytensor/discussions)
      to validate it and bring attention to it. After validation,
      you can open this issue for a more technical developer discussion.
      Check the [Contributor Guide](https://github.com/pymc-devs/pytensor/blob/main/CONTRIBUTING.md)
      if you need more information.

- type: textarea
  attributes:
    label: "Before"
    description: >
      Please fill the code snippet: How did you workaround your problem or frequent use?
      Leave empty if you found no workaround.
    render: python
  validations:
    required: false

- type: textarea
  attributes:
    label: "After"
    description: >
      How you see it implemented with a high level API without going into details
    render: python
  validations:
    required: false

- type: textarea
  attributes:
    label: "Context for the issue:"
    description: |
      Please explain how this issue affects your work, why it should be prioritized
      or add any information that did not fit Before After template.
    placeholder: |
      << your explanation here >>
  validations:
    required: false
