# This issue template was adapted from the NumPy project
# under the BSD 3-Clause "New" or "Revised" License.
# Copyright (c) 2005-2022, NumPy Developers.
# All rights reserved.


name: Post-install/importing issue
description: Report an issue if you have trouble importing or using PyMC after installation.
title: "<Please write a comprehensive title here>"
labels: [installation]

body:
- type: textarea
  attributes:
    label: "Steps to reproduce:"
    description: >
      Please describe the installation method (e.g. building from source,
      Anaconda, pip), your OS and PyMC/Python version information.
  validations:
    required: true

- type: textarea
  attributes:
    label: "Error message:"
    description: >
      Please include full error message.
    placeholder: |
      << Full traceback starting from `Traceback: ...` >>
    render: shell

- type: textarea
  attributes:
    label: "Additional information:"
    description: Please add any additional information that could help us diagnose the problem better.
