name: Miscellaneous
description: A plain template for issues which do not fall into other categories.
title: "MISC: <Please write a comprehensive title here>"

body:
- type: textarea
  attributes:
    label: Please describe the purpose of filing this issue
  validations:
    required: true
