from collections.abc import Callable

import mlx.core as mx
import numpy as np

from pytensor.link.mlx.dispatch.basic import mlx_funcify
from pytensor.link.mlx.dispatch.scalar.erf import _METAL_HEADER, _metal_constants
from pytensor.link.mlx.dispatch.scalar.helpers import _exp, _working_precision
from pytensor.link.mlx.dispatch.scalar.math import (
    _LANCZOS_COEFFS,
    _LANCZOS_G,
    _lanczos_log_gamma,
)
from pytensor.scalar.math import Erfc, GammaInc, GammaIncC


# The regularized incomplete gamma functions have no single expansion that holds over
# the whole domain, so three cover it between them:
#
#   the ascending series for P below x = a + 1,
#   the Lentz continued fraction for Q above it,
#   and Temme's uniform asymptotic expansion (DLMF 8.12) through the transition at
#   large a, where the other two need a number of terms growing with sqrt(a).
#
# The trip counts below are fixed because a is a runtime tensor -- a shape parameter,
# usually a random variable -- so nothing about it is known when the graph is built.
# Temme is what makes that affordable: its cost does not depend on a at all, and its
# accuracy improves as a grows, which is exactly where the other two fall apart.
_SERIES_TERMS = 50
_CF_TERMS = 50
# The window is set by float32 rather than float64: the series and the continued
# fraction both reach their answer through a log prefactor that subtracts two numbers of
# order a log a, so single precision loses digits in proportion to a, while Temme's form
# has no such subtraction. Widening past this trades float64 accuracy for no further
# float32 gain
_TEMME_MIN_A = 15.0
_TEMME_MIN_RATIO = 0.4
_TEMME_MAX_RATIO = 1.8

# 0.25**25 sits below float64 epsilon, so the series is exact to working precision
# everywhere it is selected
_ETA_SERIES_TERMS = 25
_ETA_SERIES_MAX_SIGMA = 0.25
# The continued fraction's zero-denominator floor. It has to be a normal at float32 as
# well as float64, or it rounds to zero there and takes both of Lentz's guards with it
_TINY = 1e-30

# d[k][n] from DLMF 8.12.12, generated by the script scipy ships at
# scipy/special/_precompute/gammainc_asy.py. Ten k by fourteen n holds 1e-13 from
# a = 15 upward across the window this uses it in; scipy's own table is larger because
# it applies the expansion further from x = a than we need to.
_TEMME_D = (
    (
        -0.3333333333333333,
        0.08333333333333333,
        -0.014814814814814815,
        0.0011574074074074073,
        0.0003527336860670194,
        -0.0001787551440329218,
        3.919263178522438e-05,
        -2.185448510679992e-06,
        -1.85406221071516e-06,
        8.296711340953087e-07,
        -1.7665952736826078e-07,
        6.707853543401498e-09,
        1.0261809784240309e-08,
        -4.382036018453353e-09,
    ),
    (
        -0.001851851851851852,
        -0.003472222222222222,
        0.0026455026455026454,
        -0.0009902263374485596,
        0.00020576131687242798,
        -4.018775720164609e-07,
        -1.8098550334489977e-05,
        7.64916091608111e-06,
        -1.6120900894563446e-06,
        4.647127802807434e-09,
        1.378633446915721e-07,
        -5.752545603517705e-08,
        1.1951628599778148e-08,
        -1.7543241719747647e-11,
    ),
    (
        0.004133597883597883,
        -0.0026813271604938273,
        0.0007716049382716049,
        2.0093878600823047e-06,
        -0.0001073665322636516,
        5.2923448829120125e-05,
        -1.2760635188618728e-05,
        3.423578734096138e-08,
        1.3721957309062934e-06,
        -6.298992138380055e-07,
        1.4280614206064242e-07,
        -2.0477098421990866e-10,
        -1.409252991086752e-08,
        6.228974084922022e-09,
    ),
    (
        0.0006494341563786008,
        0.00022947209362139917,
        -0.0004691894943952557,
        0.00026772063206283885,
        -7.561801671883977e-05,
        -2.396505113867297e-07,
        1.1082654115347302e-05,
        -5.6749528269915965e-06,
        1.4230900732435883e-06,
        -2.7861080291528143e-11,
        -1.6958404091930278e-07,
        8.099464905388083e-08,
        -1.9111168485973655e-08,
        2.3928620439808118e-12,
    ),
    (
        -0.0008618882909167117,
        0.0007840392217200666,
        -0.0002990724803031902,
        -1.4638452578843418e-06,
        6.641498215465122e-05,
        -3.968365047179435e-05,
        1.1375726970678419e-05,
        2.507497226237533e-10,
        -1.6954149536558305e-06,
        8.907507532205309e-07,
        -2.292934834000805e-07,
        2.956794137544049e-11,
        2.8865829742708783e-08,
        -1.4189739437803219e-08,
    ),
    (
        -0.00033679855336635813,
        -6.972813758365857e-05,
        0.0002772753244959392,
        -0.00019932570516188847,
        6.797780477937208e-05,
        1.419062920643967e-07,
        -1.3594048189768693e-05,
        8.018470256334202e-06,
        -2.291481176508095e-06,
        -3.252473551298454e-10,
        3.4652846491085265e-07,
        -1.8447187191171344e-07,
        4.8240967037894184e-08,
        -1.7989466721743514e-14,
    ),
    (
        0.0005313079364639922,
        -0.0005921664373536939,
        0.0002708782096718045,
        7.902353232660328e-07,
        -8.153969367561969e-05,
        5.61168275310625e-05,
        -1.8329116582843375e-05,
        -3.0796134506033047e-09,
        3.465155368803609e-06,
        -2.0291327396058603e-06,
        5.788792863149004e-07,
        2.338630673826657e-13,
        -8.828600746330484e-08,
        4.7435958880408125e-08,
    ),
    (
        0.00034436760689237765,
        5.171790908260592e-05,
        -0.00033493161081142234,
        0.0002812695154763237,
        -0.00010976582244684731,
        -1.2741009095484485e-07,
        2.7744451511563645e-05,
        -1.8263488805711332e-05,
        5.7876949497350525e-06,
        4.93875893393627e-10,
        -1.0595367014026043e-06,
        6.166714376110408e-07,
        -1.7562973359060463e-07,
        -1.2974473287015437e-12,
    ),
    (
        -0.0006526239185953094,
        0.0008394987206720873,
        -0.000438297098541721,
        -6.969091458420552e-07,
        0.00016644846642067547,
        -0.00012783517679769218,
        4.629953263691304e-05,
        4.557909867922708e-09,
        -1.0595271125805195e-05,
        6.783342904865167e-06,
        -2.1075476666258803e-06,
        -1.7213731432817144e-11,
        3.773587741611098e-07,
        -2.1867506700122867e-07,
    ),
    (
        -0.0005967612901927463,
        -7.204895416020011e-05,
        0.0006782308837667328,
        -0.0006401475260262758,
        0.00027750107634328704,
        1.819700838046515e-07,
        -8.479507117068503e-05,
        6.105192082501531e-05,
        -2.1073920183404862e-05,
        -8.858589014125599e-10,
        4.5284535953805374e-06,
        -2.8427815022504407e-06,
        8.708234177864641e-07,
        3.688610187171431e-12,
    ),
)


def _temme_eta(a, x, const):
    r"""Temme's variable, with :math:`\eta^2 / 2 = \lambda - 1 - \log \lambda`.

    Even in the ``log1p`` form the two terms cancel to the size of their own difference
    as :math:`x \to a`, which is the transition Temme exists to cover. The Maclaurin
    series of that difference has no subtraction in it at all, so it carries the
    small-:math:`\sigma` end. The loss is amplified downstream: :math:`\eta` enters an
    exponent scaled by :math:`a`, so a relative error in it comes back multiplied by
    :math:`a \eta^2 / 2`.
    """
    sigma = (x - a) / a

    series = const(0.0)
    for k in reversed(range(_ETA_SERIES_TERMS)):
        series = series * (-sigma) + const(2.0 / (k + 2.0))
    value = mx.where(
        mx.abs(sigma) <= const(_ETA_SERIES_MAX_SIGMA),
        sigma * sigma * series,
        const(-2.0) * (mx.log1p(sigma) - sigma),
    )
    return mx.sign(sigma) * mx.sqrt(mx.maximum(value, const(0.0)))


def _temme(a, x, sign, const, erfc):
    r"""One tail by the uniform asymptotic expansion, for large :math:`a` near the
    transition.

    Parameters
    ----------
    sign : float
        ``+1.0`` for :math:`Q(a, x)`, ``-1.0`` for :math:`P(a, x)`. Both tails come out
        of the same expansion, by

        .. math::
            \operatorname{erfc}(z) + \operatorname{erfc}(-z) = 2

        so each is built from terms of its own magnitude rather than as a subtraction
        from one.
    """
    eta = _temme_eta(a, x, const)

    total = const(0.0)
    a_power = const(1.0)
    for row in _TEMME_D:
        coefficient = const(row[-1])
        for value in reversed(row[:-1]):
            coefficient = coefficient * eta + const(value)
        total = total + coefficient * a_power
        a_power = a_power / a

    correction = (
        _exp(const(-0.5) * a * eta * eta, const)
        * mx.rsqrt(const(2.0 * np.pi) * a)
        * total
    )
    tail = const(0.5) * erfc(const(sign) * eta * mx.sqrt(a * const(0.5)))
    return tail + const(sign) * correction


def _gammainc_series(a, x, const):
    """``P(a, x)`` by the ascending series, for ``x`` at or below ``a + 1``."""
    term = const(1.0)
    total = const(1.0)
    for n in range(1, _SERIES_TERMS):
        term = term * x / (a + const(float(n)))
        total = total + term

    # the whole x**a exp(-x) / Gamma(a + 1) prefactor in log space, so that a large a
    # does not overflow on its way to a small answer. x = 0 is substituted rather than
    # clamped: clamping puts a * log(tiny) in the exponent, which for a small a lands on
    # a finite nonzero answer instead of the exact zero P(a, 0) has
    positive = x > const(0.0)
    log_prefactor = (
        -x
        + a * mx.log(mx.where(positive, x, const(1.0)))
        - _lanczos_log_gamma(a, const)
    )
    # x - x rather than a zero constant, so a nan argument still propagates
    return mx.where(positive, total * _exp(log_prefactor, const), x - x)


def _gammaincc_cf(a, x, const):
    """``Q(a, x)`` by the Lentz continued fraction, for ``x`` above ``a + 1``."""
    tiny = const(_TINY)
    b = x + const(1.0) - a
    c = const(1.0) / tiny
    d = const(1.0) / mx.where(b == const(0.0), tiny, b)
    h = d

    for i in range(1, _CF_TERMS):
        an = -const(float(i)) * (const(float(i)) - a)
        b = b + const(2.0)
        d = an * d + b
        d = mx.where(mx.abs(d) < tiny, tiny, d)
        c = b + an / c
        c = mx.where(mx.abs(c) < tiny, tiny, c)
        d = const(1.0) / d
        h = h * d * c

    # the x**a exp(-x) / Gamma(a) prefactor; _lanczos_log_gamma is shifted by one, so
    # Gamma(a) is its value at a - 1
    log_prefactor = -x + a * mx.log(x) - _lanczos_log_gamma(a - const(1.0), const)
    return h * _exp(log_prefactor, const)


def _incomplete_gamma(a, x, const, erfc, *, lower):
    r"""One regularized incomplete gamma tail over the whole domain.

    Three expansions cover the plane, chosen per element. Whichever tail is asked for is
    always the one the selected expansion produces at full precision: Temme supplies
    either directly, the series owns the region where :math:`Q` is order one, and the
    continued fraction owns the region where :math:`P` is, so the complement is never a
    subtraction of two nearby numbers.

    Parameters
    ----------
    lower : bool
        Return :math:`P(a, x)` when true, :math:`Q(a, x)` when false.
    """
    use_temme = (
        (a >= const(_TEMME_MIN_A))
        & (x >= const(_TEMME_MIN_RATIO) * a)
        & (x <= const(_TEMME_MAX_RATIO) * a)
    )
    use_series = ~use_temme & (x <= a + const(1.0))
    # x = inf saturates instead of reaching the continued fraction, where b = x + 1 - a is
    # itself inf and the Lentz step forms (1 / inf) * inf. Tested rather than compared
    # against a constant, so no infinity is ever materialized for mx.compile to inline
    saturated = mx.isinf(x) & (x > const(0.0))

    # Every branch runs for every element, so each is handed an argument it can survive
    # rather than the one belonging to whichever branch will actually be selected
    temme = _temme(a, mx.where(use_temme, x, a), -1.0 if lower else 1.0, const, erfc)
    series = _gammainc_series(a, mx.where(use_series, x, a * const(0.25)), const)
    fraction = _gammaincc_cf(
        a, mx.where(use_temme | use_series | saturated, a + const(2.0), x), const
    )
    if lower:
        fraction = const(1.0) - fraction
    else:
        series = const(1.0) - series

    selected = mx.where(use_temme, temme, mx.where(use_series, series, fraction))
    return mx.where(saturated, const(1.0 if lower else 0.0), selected)


# The vectorized form runs all three expansions for every element and discards two:
# timed separately under mx.compile at n = 1e6 they cost 1.6, 2.4 and 6.4 ms against
# 11.6 ms for the composite, so it is very nearly their sum. A kernel takes one branch
# and stops each series when it has converged, which for the ascending series is a
# median of 8 terms out of the 50 the graph must always unroll.
_METAL_GAMMAINC_HEADER = (
    _METAL_HEADER
    + _metal_constants(
        GI_LANCZOS=_LANCZOS_COEFFS,
        GI_TEMME_D=tuple(value for row in _TEMME_D for value in row),
        # The eta series coefficients are loop-invariant, so they are tabulated for the
        # same reason the vectorized path folds them at trace time: written inline they
        # are a division per term that only constant folding would remove
        GI_ETA_C=tuple(2.0 / (k + 2.0) for k in range(_ETA_SERIES_TERMS)),
    )
    + f"""
#define GI_SERIES_TERMS   {_SERIES_TERMS}
#define GI_CF_TERMS       {_CF_TERMS}
#define GI_ETA_TERMS      {_ETA_SERIES_TERMS}
#define GI_ETA_MAX_SIGMA  {_ETA_SERIES_MAX_SIGMA}f
#define GI_TEMME_MIN_A    {_TEMME_MIN_A}f
#define GI_TEMME_MIN_R    {_TEMME_MIN_RATIO}f
#define GI_TEMME_MAX_R    {_TEMME_MAX_RATIO}f
#define GI_TEMME_ROWS     {len(_TEMME_D)}
#define GI_TEMME_COLS     {len(_TEMME_D[0])}
#define GI_LANCZOS_N      {len(_LANCZOS_COEFFS)}
#define GI_LANCZOS_T      {_LANCZOS_G + 0.5}f
#define GI_LOG_SQRT_2PI   {float(0.5 * np.log(2.0 * np.pi))!r}f
#define GI_TINY           {_TINY}f
// just under one float32 epsilon: below this a term no longer moves the sum
#define GI_CONVERGED      1.0e-7f

static inline float gi_erfc(float value) {{
    float y = fabs(value);
    float res = (y <= ERF_THRESH) ? 1.0f - erf_series(y)
                                  : exp(-y * y) * erfcx_upper(y);
    return (value < 0.0f) ? 2.0f - res : res;
}}

// log Gamma(w + 1), shifted the same way the vectorized Lanczos helper is
static inline float gi_lgamma1p(float w) {{
    float series = GI_LANCZOS[0];
    for (int i = 1; i < GI_LANCZOS_N; ++i) series += GI_LANCZOS[i] / (w + (float)i);
    float t = w + GI_LANCZOS_T;
    return GI_LOG_SQRT_2PI + (w + 0.5f) * log(t) - t + log(series);
}}

static inline float gi_series(float a, float x) {{
    // x - x rather than 0, so a nan argument still propagates
    if (!(x > 0.0f)) return x - x;
    float term = 1.0f;
    float total = 1.0f;
    for (int n = 1; n < GI_SERIES_TERMS; ++n) {{
        term *= x / (a + (float)n);
        total += term;
        if (fabs(term) <= GI_CONVERGED * fabs(total)) break;
    }}
    return total * exp(-x + a * log(x) - gi_lgamma1p(a));
}}

static inline float gi_cf(float a, float x) {{
    float b = x + 1.0f - a;
    float c = 1.0f / GI_TINY;
    float d = 1.0f / ((b == 0.0f) ? GI_TINY : b);
    float h = d;
    for (int i = 1; i < GI_CF_TERMS; ++i) {{
        float an = -(float)i * ((float)i - a);
        b += 2.0f;
        d = an * d + b;
        if (fabs(d) < GI_TINY) d = GI_TINY;
        c = b + an / c;
        if (fabs(c) < GI_TINY) c = GI_TINY;
        d = 1.0f / d;
        float delta = d * c;
        h *= delta;
        if (fabs(delta - 1.0f) <= GI_CONVERGED) break;
    }}
    return h * exp(-x + a * log(x) - gi_lgamma1p(a - 1.0f));
}}

static inline float gi_eta(float a, float x) {{
    float sigma = (x - a) / a;
    float value;
    if (fabs(sigma) <= GI_ETA_MAX_SIGMA) {{
        float series = 0.0f;
        for (int k = GI_ETA_TERMS - 1; k >= 0; --k) {{
            series = series * (-sigma) + GI_ETA_C[k];
        }}
        value = sigma * sigma * series;
    }} else {{
        value = -2.0f * (log1p(sigma) - sigma);
    }}
    return sign(sigma) * sqrt(fmax(value, 0.0f));
}}

static inline float gi_temme(float a, float x, float sgn) {{
    float eta = gi_eta(a, x);
    float total = 0.0f;
    float a_power = 1.0f;
    float inverse_a = 1.0f / a;
    for (int k = 0; k < GI_TEMME_ROWS; ++k) {{
        int row = k * GI_TEMME_COLS;
        float coefficient = GI_TEMME_D[row + GI_TEMME_COLS - 1];
        for (int n = GI_TEMME_COLS - 2; n >= 0; --n) {{
            coefficient = coefficient * eta + GI_TEMME_D[row + n];
        }}
        total += coefficient * a_power;
        a_power *= inverse_a;
    }}
    float correction = exp(-0.5f * a * eta * eta) * rsqrt(2.0f * M_PI_F * a) * total;
    return 0.5f * gi_erfc(sgn * eta * sqrt(a * 0.5f)) + sgn * correction;
}}
"""
)


_METAL_GAMMAINC_SOURCE = """
    uint i = thread_position_in_grid.x;
    float a = (float)a_buf[i];
    float x = (float)x_buf[i];
    float res;
    if (isinf(x) && x > 0.0f) {
        // the continued fraction would form (1 / inf) * inf here and return nan
        res = GI_LOWER ? 1.0f : 0.0f;
    } else if (a >= GI_TEMME_MIN_A && x >= GI_TEMME_MIN_R * a && x <= GI_TEMME_MAX_R * a) {
        res = gi_temme(a, x, GI_SIGN);
    } else if (x <= a + 1.0f) {
        float lower = gi_series(a, x);
        res = GI_LOWER ? lower : 1.0f - lower;
    } else {
        float upper = gi_cf(a, x);
        res = GI_LOWER ? 1.0f - upper : upper;
    }
    out[i] = (T)res;
"""


_METAL_GAMMAINC_KERNELS: dict[bool, Callable | None] = {}


def _metal_gammainc_kernel(lower):
    """Build and cache the Metal kernel for one tail, or None if it cannot be built.

    The guard catches a failure to construct the kernel object. It does not catch a
    malformed source: Metal compiles lazily on first call and aborts the process rather
    than raising, so the source has no runtime safety net and the fallback cannot stand
    in for one.
    """
    if lower not in _METAL_GAMMAINC_KERNELS:
        # the trailing newline matters: MLX appends its own template declaration
        # straight after this header, and a #define running into it fails to compile
        header = (
            _METAL_GAMMAINC_HEADER
            + f"#define GI_LOWER {int(lower)}\n"
            + f"#define GI_SIGN {-1.0 if lower else 1.0}f\n"
        )
        try:
            _METAL_GAMMAINC_KERNELS[lower] = mx.fast.metal_kernel(
                name=f"pytensor_gamma{'inc' if lower else 'incc'}",
                input_names=["a_buf", "x_buf"],
                output_names=["out"],
                header=header,
                source=_METAL_GAMMAINC_SOURCE,
            )
        except Exception:
            _METAL_GAMMAINC_KERNELS[lower] = None
    return _METAL_GAMMAINC_KERNELS[lower]


def _metal_gammainc_call(a, x, lower):
    """Evaluate one tail through its Metal kernel, or return None to fall back.

    Metal has no float64 and the kernel needs the GPU stream, which between them leave
    exactly the case the vectorized path handles least well and float64 needs least: the
    default device at single precision.
    """
    if (
        a.dtype != mx.float32
        or x.dtype != mx.float32
        or not mx.metal.is_available()
        or mx.default_device() != mx.gpu
    ):
        return None
    kernel = _metal_gammainc_kernel(lower)
    if kernel is None:
        return None
    # The kernel indexes two flat buffers in lockstep, so the operands are broadcast
    # against each other first: the op admits a scalar shape parameter against an array
    # of values, and a 0-d input binds as a value rather than a pointer and cannot be
    # subscripted
    shape, value = mx.broadcast_arrays(a, x)
    flat_shape, flat_value = shape.reshape(-1), value.reshape(-1)
    (out,) = kernel(
        inputs=[flat_shape, flat_value],
        template=[("T", flat_value.dtype)],
        grid=(flat_value.size, 1, 1),
        threadgroup=(min(256, max(flat_value.size, 1)), 1, 1),
        output_shapes=[flat_value.shape],
        output_dtypes=[flat_value.dtype],
    )
    return out.reshape(shape.shape)


def _incomplete_gamma_dispatch(lower):
    """Build the callable one of the two ops dispatches to."""
    erfc = mlx_funcify(Erfc())

    def incomplete_gamma(a, x):
        z, const, out_dtype = _working_precision(x)
        shape = mx.array(a).astype(z.dtype)
        out = _metal_gammainc_call(shape, z, lower)
        if out is None:
            out = _incomplete_gamma(shape, z, const, erfc, lower=lower)
        return out.astype(out_dtype)

    return incomplete_gamma


@mlx_funcify.register(GammaIncC)
def mlx_funcify_GammaIncC(op, **kwargs):
    return _incomplete_gamma_dispatch(lower=False)


@mlx_funcify.register(GammaInc)
def mlx_funcify_GammaInc(op, **kwargs):
    return _incomplete_gamma_dispatch(lower=True)
